name: Deploy CLI
on: push
jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
        - name: Hola Mundo
          run: echo "Hola mundo"
    second_job:
      if: ${{github.ref == 'refs/heads/main'}}
      needs: first_job
      runs-on: ubuntu-latest
      steps:
        - name: Hola mundo 2
          run: echo "Hineill 2"